import type { LucideIcon } from 'lucide-react';
import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  Heart,
  Home,
  Image,
  Info,
  Link,
  Mail,
  Map,
  Menu,
  MessageCircle,
  Phone,
  Plus,
  Search,
  Settings,
  Share,
  ShoppingCart,
  Star,
  Trash,
  Upload,
  User,
  X,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  Heart,
  Home,
  Image,
  Info,
  Link,
  Mail,
  Map,
  Menu,
  MessageCircle,
  Phone,
  Plus,
  Search,
  Settings,
  Share,
  ShoppingCart,
  Star,
  Trash,
  Upload,
  User,
  X,
};

// The label/value pairs Field's icon-picker feeds to Select, derived once
// from ICON_MAP — exported (see index.ts) so a custom renderPanel can
// reach icon-picker parity without rebuilding this itself, per #236/#237.
export const ICON_OPTIONS = Object.entries(ICON_MAP).map(([name, Icon]) => ({
  label: (
    <span className="flex items-center gap-2">
      <Icon size={14} />
      {name}
    </span>
  ),
  value: name,
}));
