import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/index.tsx',
    'src/utils/index.ts',
    'src/utils/ast/index.ts',
    'src/utils/tailwind/index.ts',
  ],
  format: ['esm'],
  dts: { build: true },
  outDir: 'dist',
  clean: true,
  sourcemap: true,
  treeshake: true,
  unbundle: true,
  inlineOnly: [
    /^@babel\//,
    /^@codemirror\//,
    /^@jridgewell\//,
    '@xobotyi/scrollbar-width',
    '@jbpark/use-hooks',
    '@marijn/find-cluster-break',
    'clsx',
    'copy-to-clipboard',
    'debug',
    'fast-deep-equal',
    'fast-shallow-equal',
    'has-flag',
    'js-cookie',
    'js-tokens',
    'jsesc',
    'ms',
    'nanoid',
    'nano-css',
    'picocolors',
    'react-universal-interface',
    'react-use',
    'screenfull',
    'set-harmonic-interval',
    'style-mod',
    'supports-color',
    'tailwind-merge',
    'throttle-debounce',
    'toggle-selection',
    'ts-easing',
    'tslib',
    'w3c-keyname',
  ],
});
