import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated from the docs/ folder structure — each page sets its own
// sidebar_position in front matter.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
